baseurl = "https://toxi.nu/"
languageCode = "en-us"
pygmentscodefences = true
pygmentsuseclasses = true
theme = "toxinu"
title = "toxinu"
[params]
description = "Developer, hacker, music listener and books reader."
email = "toxinu@gmail.com"
github = "toxinu"
twitter = "toxinu_"
[permalinks]
blog = "blog/:slug/"
fixed = ":title/"
