baseURL = "/"
languageCode = "en-us"
pygmentscodefences = true
pygmentsuseclasses = true
theme = "toxinu"
title = "toxinu"
publishDir = ".."
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
[params]
description = "Developer, hacker, music listener and books reader."
email = "toxinu@gmail.com"
github = "toxinu"
gitlab= "toxinu"
twitter = "toxinu_"
[permalinks]
blog = "blog/:slug/"
fixed = ":title/"
