baseURL = "/"
languageCode = "en-us"
pygmentscodefences = true
pygmentsuseclasses = true
theme = "toxinude"
title = "toxinu"
publishDir = "../docs"
copyright = "toxinu"
googleAnalytics = "UA-178253729-1"
googleAnalyticsAsync = true
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
[params]
# Theme
showAllPostsOnHomePage = true
showPaginationHomePage = false
rss = true
# Other
email = "toxinu@gmail.com"
github = "toxinu"
gitlab= "toxinu"
twitter = ""
instagram = "toxinu_"
[[params.photography]]
  name = "Buildings reaching the blue sky at Minato-ku (港区)"
  date = "Tokyo, Japan. Sprin 2021"
  linkSmall = "/images/photography/blue-sky-with-building.jpg"
  linkMedium = "/images/photography/blue-sky-with-building.jpg"
  vertical = false
[[params.photography]]
  name = "Sakura forest (吉野町)"
  date = "Yoshino, Japan. Summer 2020"
  linkSmall = "/images/photography/yoshino-sakura.jpg"
  linkMedium = "/images/photography/yoshino-sakura.jpg"
  vertical = true
[[params.photography]]
  name = "Rainy day under a bridge at Fukishima-ku (福島区)"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/osaka-raining-bridge.jpg"
  vertical = false
[[params.photography]]
  name = "Kimchi shop during summer (生野コリアタウン)"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/osaka-kimchi-shop.jpg"
  vertical = false
[[params.photography]]
  name = "Sunset at Abeno Harukas (あべのハルカス)"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/osaka-abeno-harukas.jpg"
  vertical = true
[[params.photography]]
  name = "Colorful Japanese street"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/osaka-colorful-street.jpg"
  vertical = false
[[params.photography]]
  name = "Go players"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/osaka-go-players.jpg"
  vertical = false
[[params.photography]]
  name = "Old temple stand in wood (宝山寺)"
  date = "Hōzan-ji, Japan. Summer 2020"
  linkMedium = "/images/photography/hozan-ji-summer.jpg"
  vertical = false
[[params.photography]]
  name = "Port of Kobe in the Autumn"
  date = "Kobe, Japan. Autumn 2020"
  linkMedium = "/images/photography/kobe-automn.jpg"
  vertical = false
[[params.photography]]
  name = "Old shop keeper in Tokyo street"
  date = "Tokyo Japan. June, 2021"
  linkMedium = "/images/photography/shop-keeper-tokyo.jpg"
  vertical = false
[[params.photography]]
  name = "People in the train using the Ginza Line"
  date = "Tokyo, Japan. June, 2021"
  linkMedium = "/images/photography/people-in-the-ginza-line.jpg"
  vertical = false
[[params.photography]]
  name = "Thirsty dog in the street"
  date = "Tokyo, Japan. June 2021"
  linkMedium = "/images/photography/thirsty-dog-in-the-street.jpg"
  vertical = false
[[params.photography]]
  name = "Lady ordering food at a shop"
  date = "Tokyo, Japan. June 2021"
  linkMedium = "/images/photography/lady-ordering-food.jpg"
  vertical = false
[[params.photography]]
  name = "Nightly shoppers at a street corner"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/nightly-shoppers.jpg"
  vertical = false
[[params.photography]]
  name = "Bike shop"
  date = "Osaka, Japan. Summer 2020"
  linkMedium = "/images/photography/bike-shop-osaka.jpg"
  vertical = false
[[params.photography]]
  name = "Buddha statue (宝山寺)"
  date = "Hōzan-ji, Japan. Summer 2020"
  linkMedium = "/images/photography/buddha-statue.jpg"
  vertical = false
[permalinks]
blog = "blog/:slug/"
fixed = ":title/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Photography"
url = "/photography/"
weight = 2
[[menu.main]]
name = "Journal"
url = "/blog/"
weight = 3
[[menu.main]]
name = "About"
url = "/about/"
weight = 4
